name: playwright-docker-smoke
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy .env if exists
        run: |
          if [ -f .env ]; then
            cp .env .env.ci
          fi

      - name: Build Docker image
        run: docker build -t my-playwright .

      - name: Run Playwright smoke test in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/test-results:/app/test-results \
            -e PLAYWRIGHT_HTML_REPORT=/app/test-results/report \
            my-playwright \
            npx playwright test tests/smoke.spec.ts

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test-results/
