name: Playwright Tests & Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      BASE_URL: https://qauto.forstudy.space
      HTTP_USERNAME: guest
      HTTP_PASSWORD: welcome2qauto
      TEST_USER2_LOGIN: testuser@example.com
      TEST_USER2_PASSWORD: typeTest1234

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run only apiCars tests
        run: npx playwright test tests/apiCars.spec.ts

      - name: Upload Playwright report artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Playwright report artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: out

      - name: Setup Pages with enablement
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
