name: Playwright Tests in Docker (apiCars only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-playwright .

      - name: Run ONLY apiCars tests inside Docker
        run: |
          docker run --rm \
            -e BASE_URL=https://qauto.forstudy.space \
            -e HTTP_USERNAME=guest \
            -e HTTP_PASSWORD=welcome2qauto \
            -e TEST_USER2_LOGIN=testuser@example.com \
            -e TEST_USER2_PASSWORD=typeTest1234 \
            -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
            -v ${{ github.workspace }}/test-results:/app/test-results \
            my-playwright \
            npx playwright test tests/apiCars.spec.ts

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
